
export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const LOG_OUT_REQUEST = 'LOG_OUT_REQUEST';
