export const CREATE_TEST = 'CREATE_TEST';
export const FETCH_ALL_TESTS = 'FETCH_ALL_TESTS';
export const FETCH_TEST_BY_ID = 'FETCH_TEST_BY_ID';
export const UPDATE_TEST = 'UPDATE_TEST';
export const DELETE_TEST = 'DELETE_TEST';

export const CREATE_QUESTION = 'CREATE_QUESTION';
export const EDIT_QUESTION = 'EDIT_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';

export const CREATE_ANSWERS = 'CREATE_ANSWERS';
export const UPDATE_ANSWERS = 'UPDATE_ANSWERS';
export const MOVE_ANSWERS = 'MOVE_ANSWERS';
export const DELETE_ANSWERS = 'DELETE_ANSWERS';
