import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import classNames from 'classnames/bind';

import { BoxContainer } from '@/components/layout/box-container';
import { Header } from '@/components/ui/header';
import { Footer } from '@/components/ui/footer';

import styles from './layout.module.scss';

import './globals.scss';
import { Providers } from '@/components/utils/providers';

const cx = classNames.bind(styles);

const inter = Inter({
	subsets: ['latin', 'cyrillic', 'cyrillic-ext'],
	weight: ['400', '500', '600', '900'],
	adjustFontFallback: true,
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<Providers>
			<html lang="en">
				<body className={cx(inter.className)}>
					<div className={cx('layout')}>
						<Header className={cx('layout__header')} />
						<main className={cx('layout__main')}>
							<BoxContainer>{children}</BoxContainer>
						</main>
						<Footer className={cx('layout__footer')} />
					</div>
				</body>
			</html>
		</Providers>
	);
}
